raw_bc: rawdata_example/barcode_sequencing
raw_lib: rawdata_example/library_sequencing
sample_info_bc: rawdata_example/sample_info_bc
pipeline: /lustre/grp/cyllab/jianfc/Antibody/develop/dms-pipeline

target_ref: reference/target_ref
wt_seqs: reference/wt_seqs

output: output_example

batches: all # specify the batch names to process, or 'all' to process all batches

fq_suffix: '*q.gz'
R2_pattern: '((_2)|(_R2))\.f(ast)?q\.gz'

barcode_count:
  lowq: 20  # Minimum sequencing quality required.
  allowed_lowq: 1  # Permits one low-quality nucleotide per read. Recommended for barcodes >25 in length.
  max_distance: 0  # When >0, searches for the closest match in the dictionary. If 0, requires exact match to a dictionary barcode.
  min_dist_diff: 3  # When max_distance > 0, ensures the second closest barcode is not within this distance to the closest, to prevent ambiguous matches. Ignored if max_distance = 0.

calc_escape_scores:
  min_ref_count: 1 # Recommend: 5
  min_variant_support: 1 # Recommend: 2
  # normalize_to_WT: true  # Normalizes fractions by dividing by the enrichment fraction of barcodes without amino acid mutations, then applies log10 transformation.
  norm_lower: 0.01
  norm_upper: 0.995  # Normalizes escape scores to [0, 1] with quantile cutoffs. Eg. For lower=0.01 and upper=0.995, scores below 1% or above 99.5% quantiles are set to 0 and 1, respectively.
  # flexible_upper: true  # Adjusts the upper quantile if not suitable (e.g., if the 99.5% quantile is not >10 times the 1% quantile), using the maximum score as the upper bound.

  filter_on_single: true
  filter_on_variant: true

  keep_missing: true # keep the escape scores for mutants with missing values in the variant/mut filters
  calc_no_filter: true # also output the results without any filters
  include_stop: false

  epistasis: dms_variants # dms_variants | dms_variants_linear | sigmoid
  
  QC: # threshold for escape profile quality filters
    max_WT_enrichment: 0.3
  
libinfo:
  RSV-F-UP-merged:
    target: RSV-F
  RSV-F-lib1:
    target: RSV-F
    single_filters: 
      expr_avg: reference/filters/RSV-F/expr_single_20240401_RSV-F-lib.csv
    variant_filters: 
      delta_ML_meanF: 
        - reference/filters/RSV-F/expr_RSV-F-lib1_20240401.csv
  RSV-F-lib2:
    target: RSV-F
    single_filters: 
      expr_avg: reference/filters/RSV-F/expr_single_20240401_RSV-F-lib.csv
    variant_filters: 
      delta_ML_meanF: 
        - reference/filters/RSV-F/expr_RSV-F-lib2_20240401.csv
  RSV-F-Full-lib1:
    target: RSV-F-Full

ccs_align:
  cpu_per_task: 8

library_merge: # define merged libraries
  RSV-F:
    RSV-F-UP-merged:
      - RSV-F-lib1
      - RSV-F-lib2

exclude_antibody_names: # The following antibody names will be ignored while calculating the escape scores
  - 'None'
  - 'none'
  - ''
  - 'empty'
  - 'Empty'

sample_name_replace: # The following characters are not allowed and will be replaced by a hyphen
  '/': '-'
  ' ': '-'
  '.': '-'

parse_specs: 
  default:
    query_clip5: 6
    query_clip3: 6
    termini5:
      filter:
        clip5: 3
        mutation_nt_count: 1
        mutation_op_count: null
    gene:
      filter:
        mutation_nt_count: 45
        mutation_op_count: null
      return: [mutations, accuracy]
    spacer:
      filter:
        mutation_nt_count: 2
        mutation_op_count: null
    barcode:
      filter:
        mutation_nt_count: 0
        mutation_op_count: null
      return: [sequence, accuracy]
    termini3:
      filter:
        clip3: 3
        mutation_nt_count: 1
        mutation_op_count: null

default_template: reference/target_ref/default_template.txt

default_libinfo:
  ref_numbering_seq: reference/wt_seqs/WT_RSV_A2_ref.fasta
  bclen: 26
  min_variant: # default values
    delta_ML_meanF: -1.2
  min_single: # default values
    expr_avg: -1.2