name: dms-pipeline
channels:
 - conda-forge
 - bioconda
dependencies:
 - python=3.12
 - biopython>=1.83
 - numpy>=2.0
 - pandas
 - pyyaml
 - scipy
 - altair-all
 - samtools
 - jax=0.4.31
 - optax
 - snakemake>=8
 - snakemake-executor-plugin-cluster-generic
 - pip:
   - alignparse
   - binarymap
   - dms_variants